### ISSUE TITLE
OrderSummary stylings are missing on upgrade to cc v9

### ISSUE THREAD

**Issue by cknabe** [carbon-design-system/carbon-addons-cloud-react#13]
## Detailed description

> Describe in detail the issue you're having.
When upgrading carbon-components from v8 to v9 I lose the styling we used to have for the OrderSummary.

> Is this a feature request (new component, new icon), a bug, or a general issue?
More likely something I'm not doing right

> Is this issue related to a specific component?
OrderSummary

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected there to be slight subtle changes to coloring, shading, contrast, etc.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
    "carbon-addons-cloud": "^2.1.0",
    "carbon-addons-cloud-react": "^1.2.0",
    "carbon-components": "^9.1.0",
    "carbon-components-react": "^6.6.2",
    "carbon-icons": "^7.0.7",

upgraded from 
    "carbon-addons-cloud": "^2.0.1",
    "carbon-addons-cloud-react": "^1.1.4",
    "carbon-components": "^8.16.8",
    "carbon-components-react": "^6.4.2",
    "carbon-icons": "^7.0.6",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Gen1.VSI/BM order forms. No pressing dates.

It 'reproduces' in the sandbox, but maybe I don't have it setup properly?
https://codesandbox.io/s/y215yx9o5v

![image](https://user-images.githubusercontent.com/13582620/41789283-61e018f4-7614-11e8-93c2-58c18b9dff01.png)
In the picture, there is no styling for the bx--order-header-title.

In prod and in the storybook for the component I see the following styling for the same class:
![image](https://user-images.githubusercontent.com/13582620/41789321-7feda802-7614-11e8-8f58-51d26016b4d1.png)

**Comment by cknabe** [comment]
There are some other styling differences that I would think are not working correctly:
![image](https://user-images.githubusercontent.com/13582620/41789389-be3505d8-7614-11e8-8f0b-193867063e4b.png)

bx--order-total-text for example is missing its styling as well

**Comment by cknabe** [comment]
I did recently upgrade all of our package.json libraries and everything still looked good. The only change in my current branch is updating from carbon components v8 to v9, and that's when the styling goes away. I can still see that the stylings are in the latest version of cc: https://github.com/carbon-design-system/carbon-addons-cloud/blob/master/src/components/order-summary/_order-summary.scss

It must be something silly I'm doing wrong.

**Comment by cknabe** [comment]
This can be safely closed. It was my fault. Because the OrderSummary was split off into this repository, it now requires a separate css to be pulled in. Sorry for the inconvenience.

**Comment by asudoh** [comment]
No worries - Thank you for trying to report an issue anyway @cknabe!
